version: '3.8'

services:
  theralert:
    image: awaghray/theralert:latest
    container_name: theralert
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NODE_ENV: production
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_SERVER: ${EMAIL_SERVER} # Optional

      # Explicitly pass these individual DB variables to the Next.js app
      # The 'host' will be the service name of your database container
      DB_HOST: db # <--- NEW: Points to the 'db' service
      DB_USER: ${DB_USER} # <--- NEW: Read from .env
      DB_PASSWORD: ${DB_PASSWORD} # <--- NEW: Read from .env
      DB_NAME: ${DB_NAME} # <--- NEW: Read from .env

    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: theralert-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - theralert_db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  theralert_db_data: