version: '3.8'

services:
  theralert:
    image: awaghray/theralert:latest
    container_name: theralert
    ports:
      - "3002:3002"
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NODE_ENV: production
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}

      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: theralert-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      # IMPORTANT: Set default authentication plugin for new users to mysql_native_password
      # This resolves compatibility issues with older MySQL clients like the one in Alpine's mysql-client package.
      # This is suitable for internal Docker network connections.
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password # <--- NEW LINE
    volumes:
      - theralert_db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  theralert_db_data: