import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='nav1'>
          <ul className='nav_links'>
            <h1><Link href="/">Therativity</Link></h1>
            <h1><Link href="/calendar">Calendar</Link></h1>
            <h1><Link href="/log">Log</Link></h1>
            <h1><Link href="/about">About</Link></h1>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
